# Generated by Django 4.2.4 on 2023-08-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_remove_page_user_page_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, max_length=200, upload_to=''),
        ),
    ]
