version: '3.7'
services:
  db:
    image: postgres:12.9
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file:
     - ./link_storage_service/.env


  web:
    build: .
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db:db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432



volumes:
  postgres_data: